namespace Philiprehberger.MimeDetect;

/// <summary>
/// Internal mapping of file extensions to MIME types.
/// </summary>
internal static class ExtensionMap
{
    /// <summary>
    /// Dictionary mapping lowercase file extensions (without leading dot) to MIME type strings.
    /// </summary>
    internal static readonly Dictionary<string, string> Map = new(StringComparer.OrdinalIgnoreCase)
    {
        // Images
        { "png", "image/png" },
        { "jpg", "image/jpeg" },
        { "jpeg", "image/jpeg" },
        { "jpe", "image/jpeg" },
        { "jfif", "image/jpeg" },
        { "gif", "image/gif" },
        { "bmp", "image/bmp" },
        { "dib", "image/bmp" },
        { "webp", "image/webp" },
        { "tiff", "image/tiff" },
        { "tif", "image/tiff" },
        { "ico", "image/x-icon" },
        { "svg", "image/svg+xml" },
        { "svgz", "image/svg+xml" },
        { "heic", "image/heic" },
        { "heif", "image/heif" },
        { "avif", "image/avif" },
        { "psd", "image/vnd.adobe.photoshop" },
        { "exr", "image/x-exr" },
        { "raw", "image/x-raw" },
        { "cr2", "image/x-canon-cr2" },
        { "nef", "image/x-nikon-nef" },
        { "arw", "image/x-sony-arw" },
        { "dng", "image/x-adobe-dng" },
        { "jxl", "image/jxl" },
        { "apng", "image/apng" },
        { "cur", "image/x-icon" },

        // Audio
        { "mp3", "audio/mpeg" },
        { "wav", "audio/wav" },
        { "ogg", "audio/ogg" },
        { "oga", "audio/ogg" },
        { "flac", "audio/flac" },
        { "aac", "audio/aac" },
        { "m4a", "audio/mp4" },
        { "wma", "audio/x-ms-wma" },
        { "opus", "audio/opus" },
        { "mid", "audio/midi" },
        { "midi", "audio/midi" },
        { "aiff", "audio/aiff" },
        { "aif", "audio/aiff" },
        { "aifc", "audio/aiff" },
        { "amr", "audio/amr" },
        { "au", "audio/basic" },
        { "ra", "audio/x-realaudio" },
        { "weba", "audio/webm" },
        { "ac3", "audio/ac3" },
        { "ape", "audio/x-ape" },
        { "mka", "audio/x-matroska" },

        // Video
        { "mp4", "video/mp4" },
        { "m4v", "video/mp4" },
        { "avi", "video/x-msvideo" },
        { "webm", "video/webm" },
        { "mov", "video/quicktime" },
        { "flv", "video/x-flv" },
        { "wmv", "video/x-ms-wmv" },
        { "mkv", "video/x-matroska" },
        { "mpg", "video/mpeg" },
        { "mpeg", "video/mpeg" },
        { "mpe", "video/mpeg" },
        { "3gp", "video/3gpp" },
        { "3g2", "video/3gpp2" },
        { "ts", "video/mp2t" },
        { "mts", "video/mp2t" },
        { "m2ts", "video/mp2t" },
        { "ogv", "video/ogg" },
        { "asf", "video/x-ms-asf" },
        { "vob", "video/x-ms-vob" },
        { "divx", "video/x-msvideo" },
        { "f4v", "video/mp4" },
        { "rm", "video/vnd.rn-realvideo" },
        { "rmvb", "video/vnd.rn-realvideo" },
        { "swf", "application/x-shockwave-flash" },

        // Documents
        { "pdf", "application/pdf" },
        { "doc", "application/msword" },
        { "docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
        { "dot", "application/msword" },
        { "dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template" },
        { "xls", "application/vnd.ms-excel" },
        { "xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
        { "xlt", "application/vnd.ms-excel" },
        { "xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template" },
        { "ppt", "application/vnd.ms-powerpoint" },
        { "pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
        { "pot", "application/vnd.ms-powerpoint" },
        { "potx", "application/vnd.openxmlformats-officedocument.presentationml.template" },
        { "odt", "application/vnd.oasis.opendocument.text" },
        { "ods", "application/vnd.oasis.opendocument.spreadsheet" },
        { "odp", "application/vnd.oasis.opendocument.presentation" },
        { "rtf", "application/rtf" },
        { "tex", "application/x-tex" },
        { "latex", "application/x-latex" },
        { "epub", "application/epub+zip" },
        { "mobi", "application/x-mobipocket-ebook" },
        { "pages", "application/vnd.apple.pages" },
        { "numbers", "application/vnd.apple.numbers" },
        { "key", "application/vnd.apple.keynote" },
        { "ps", "application/postscript" },
        { "eps", "application/postscript" },
        { "xps", "application/vnd.ms-xpsdocument" },

        // Archives
        { "zip", "application/zip" },
        { "gz", "application/gzip" },
        { "gzip", "application/gzip" },
        { "tar", "application/x-tar" },
        { "tgz", "application/gzip" },
        { "bz2", "application/x-bzip2" },
        { "7z", "application/x-7z-compressed" },
        { "rar", "application/vnd.rar" },
        { "xz", "application/x-xz" },
        { "zst", "application/zstd" },
        { "lz", "application/x-lzip" },
        { "lzma", "application/x-lzma" },
        { "lzh", "application/x-lzh-compressed" },
        { "cab", "application/vnd.ms-cab-compressed" },
        { "iso", "application/x-iso9660-image" },
        { "dmg", "application/x-apple-diskimage" },
        { "deb", "application/x-debian-package" },
        { "rpm", "application/x-rpm" },
        { "jar", "application/java-archive" },
        { "war", "application/java-archive" },
        { "ear", "application/java-archive" },
        { "apk", "application/vnd.android.package-archive" },
        { "crx", "application/x-chrome-extension" },
        { "cpio", "application/x-cpio" },
        { "ar", "application/x-archive" },
        { "z", "application/x-compress" },

        // Application / Executable
        { "exe", "application/vnd.microsoft.portable-executable" },
        { "dll", "application/vnd.microsoft.portable-executable" },
        { "msi", "application/x-msi" },
        { "elf", "application/x-elf" },
        { "wasm", "application/wasm" },
        { "class", "application/java-vm" },
        { "so", "application/x-sharedlib" },
        { "dylib", "application/x-mach-binary" },
        { "com", "application/x-msdos-program" },
        { "bat", "application/x-msdos-program" },
        { "cmd", "application/x-msdos-program" },
        { "app", "application/x-mach-binary" },

        // Fonts
        { "ttf", "font/ttf" },
        { "otf", "font/otf" },
        { "woff", "font/woff" },
        { "woff2", "font/woff2" },
        { "eot", "application/vnd.ms-fontobject" },
        { "ttc", "font/collection" },

        // Database
        { "sqlite", "application/vnd.sqlite3" },
        { "sqlite3", "application/vnd.sqlite3" },
        { "db", "application/vnd.sqlite3" },
        { "mdb", "application/x-msaccess" },
        { "accdb", "application/msaccess" },

        // Text / Code
        { "txt", "text/plain" },
        { "csv", "text/csv" },
        { "tsv", "text/tab-separated-values" },
        { "log", "text/plain" },
        { "md", "text/markdown" },
        { "markdown", "text/markdown" },
        { "html", "text/html" },
        { "htm", "text/html" },
        { "xhtml", "application/xhtml+xml" },
        { "xml", "application/xml" },
        { "json", "application/json" },
        { "jsonl", "application/x-ndjson" },
        { "ndjson", "application/x-ndjson" },
        { "yaml", "application/x-yaml" },
        { "yml", "application/x-yaml" },
        { "toml", "application/toml" },
        { "ini", "text/plain" },
        { "cfg", "text/plain" },
        { "conf", "text/plain" },
        { "css", "text/css" },
        { "js", "text/javascript" },
        { "mjs", "text/javascript" },
        { "cjs", "text/javascript" },
        { "typescript", "text/typescript" },
        { "tsx", "text/tsx" },
        { "jsx", "text/jsx" },
        { "cs", "text/x-csharp" },
        { "java", "text/x-java-source" },
        { "py", "text/x-python" },
        { "rb", "text/x-ruby" },
        { "go", "text/x-go" },
        { "rs", "text/x-rust" },
        { "c", "text/x-c" },
        { "cpp", "text/x-c++src" },
        { "h", "text/x-c" },
        { "hpp", "text/x-c++hdr" },
        { "swift", "text/x-swift" },
        { "kt", "text/x-kotlin" },
        { "scala", "text/x-scala" },
        { "php", "text/x-php" },
        { "sh", "application/x-sh" },
        { "bash", "application/x-sh" },
        { "zsh", "application/x-sh" },
        { "fish", "application/x-sh" },
        { "ps1", "application/x-powershell" },
        { "sql", "application/sql" },
        { "graphql", "application/graphql" },
        { "wsdl", "application/wsdl+xml" },
        { "rss", "application/rss+xml" },
        { "atom", "application/atom+xml" },
        { "ics", "text/calendar" },
        { "vcf", "text/vcard" },
        { "rtx", "text/richtext" },
        { "diff", "text/x-diff" },
        { "patch", "text/x-diff" },
        { "proto", "text/x-protobuf" },
        { "lock", "text/plain" },
        { "env", "text/plain" },

        // Web
        { "map", "application/json" },
        { "webmanifest", "application/manifest+json" },

        // Misc
        { "bin", "application/octet-stream" },
        { "dat", "application/octet-stream" },
        { "bak", "application/octet-stream" },
        { "tmp", "application/octet-stream" },
    };
}
